[package]
name = "ani-cli-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.7.1"
reqwest = "0.11.6"      
structopt = "0.3.25"
tokio = { version = "1.12.0", features = ["full"] }
owo-colors = "3.0.1"
