[package]
name = "ani-cli-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ani-cli"
path = "src/main.rs"

[dependencies]
scraper = "0.12.0"
structopt = "0.3.25"
ureq = { version = "2.3.0" }
owo-colors = "3.0.1"
